name: choose
adopt-info: choose
summary: Human-friendly and fast alternative to cut and (sometimes) awk
description: |
    This is choose, a human-friendly and fast alternative to cut and (sometimes) awk.
  
    USAGE:
        `choose [FLAGS] [OPTIONS] <choices>...`

    FLAGS:
    ```
        -c, --character-wise    Choose fields by character number
        -d, --debug             Activate debug mode
        -x, --exclusive         Use exclusive ranges, similar to array indexing in many programming languages
        -h, --help              Prints help information
        -n, --non-greedy        Use non-greedy field separators
        -V, --version           Prints version information
    ```
    OPTIONS:
    ```
        -f, --field-separator <field-separator>
                Specify field separator other than whitespace, using Rust `regex` syntax

        -i, --input <input>                                      Input file
        -o, --output-field-separator <output-field-separator>    Specify output field separator
    ```
    ARGS:
    ```
        <choices>...    Fields to print. Either a, a:b, a..b, or a..=b, where a and b are integers. The beginning or end
                        of a range can be omitted, resulting in including the beginning or end of the line,
                        respectively. a:b is inclusive of b (unless overridden by -x). a..b is exclusive of b and a..=b
                        is inclusive of b
    ```
    
license: GPL-3.0
source-code: https://github.com/theryangeary/choose
issues: https://github.com/kz6fittycent/choose/issues
website: https://asciinema.org/a/315932?autoplay=1
contact: https://github.com/kz6fittycent/choose
icon: snap/local/choose.png
base: core24
grade: stable 
confinement: strict
compression: lzo

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  s390x:
    build-on: [s390x]
    build-for: [s390x]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
  armhf:
    build-on: [armhf]
    build-for: [armhf]
  ppc64el:
    build-on: [ppc64el]
    build-for: [ppc64el]

apps:
  choose:
    command: bin/choose
    plugs:
      - home
      
parts:
  choose:
    source: https://github.com/theryangeary/choose
    source-type: git
    plugin: rust
    build-packages:
      - cargo
    override-pull: |
      craftctl default
      craftctl set version="$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"       
